### ISSUE TITLE
使用serverless平台创建nest应用出错

### ISSUE THREAD

**Issue by FrankyLee-dev** [serverless/serverless-tencent#112]
### BUG 描述:

使用serverless平台创建nest应用出错。

### 复现步骤:

1. 选择框架
![image](https://user-images.githubusercontent.com/17977044/148724297-7686bd2d-bccd-4120-a976-3184a0c799c0.png)
2. 选择示例代码
![image](https://user-images.githubusercontent.com/17977044/148724383-e99bad9b-d6e1-45d2-8cb0-dae11a4d60fa.png)
3.完成

### 预期结果:

部署成功

### 实际结果:
Error: "src.hook" 执行失败: "npm run build", 错误信息: RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded

### 调试信息:    
[2022-01-10 14:10:43] + rm code.zip
[2022-01-10 14:10:43] + env
[2022-01-10 14:10:43] JENKINS_HOME=/var/lib/jenkins
[2022-01-10 14:10:43] CI_BUILD_ID=15133966
[2022-01-10 14:10:43] JOB_ID=1018488
[2022-01-10 14:10:43] PROJECT_TOKEN_GK=******
[2022-01-10 14:10:43] MAIL=/var/mail/root
[2022-01-10 14:10:43] PACKER_BIN=/root/programs/packer_1.6.0_linux_amd64
[2022-01-10 14:10:43] USER=root
[2022-01-10 14:10:43] HELM_BIN=/root/programs/helm-v2.16.9-linux-amd64/linux-amd64
[2022-01-10 14:10:43] CI=true
[2022-01-10 14:10:43] RUN_CHANGES_DISPLAY_URL=http://124.223.43.228:15730/job/cci-14726523-392077/1/display/redirect?page=changes
[2022-01-10 14:10:43] CI_BUILD_NUMBER=1
[2022-01-10 14:10:43] SHLVL=1
[2022-01-10 14:10:43] NODE_LABELS=master
[2022-01-10 14:10:43] HUDSON_URL=http://124.223.43.228:15730/
[2022-01-10 14:10:43] TERRAFORM_BIN=/root/programs/terraform_0.12.26_linux_amd64
[2022-01-10 14:10:43] HOME=/root
[2022-01-10 14:10:43] GRADLE_BIN=/root/programs/gradle-7.0.2/bin
[2022-01-10 14:10:43] PACK_BIN=/root/programs/pack-v0.14.2-linux
[2022-01-10 14:10:43] BUILD_URL=http://124.223.43.228:15730/job/cci-14726523-392077/1/
[2022-01-10 14:10:43] DOCKER_REGISTRY_CREDENTIALS_ID=c6b4979c-3237-4481-bad5-4cbe0bacf22e
[2022-01-10 14:10:43] MAVEN_BIN=/root/programs/apache-maven-3.6.3/bin
[2022-01-10 14:10:43] HUDSON_COOKIE=712d0112-cad8-4a92-8062-55743e30019e
[2022-01-10 14:10:43] JENKINS_SERVER_COOKIE=durable-eaea33d8b70cee58f706e622dc5f25c1
[2022-01-10 14:10:43] PROJECT_API_URL=https://serverless-100009469796.coding.net/api/user/serverless-100009469796/project/
[2022-01-10 14:10:43] LC_CTYPE=zh_CN.UTF-8
[2022-01-10 14:10:43] CCI_CURRENT_TEAM=serverless-100009469796
[2022-01-10 14:10:43] BUILD_PACK_BIN=/root/programs/pack-v0.14.2-linux
[2022-01-10 14:10:43] CI_ENV_FILE=/tmp/dynamic.env
[2022-01-10 14:10:43] WORKSPACE=/root/workspace
[2022-01-10 14:10:43] PROJECT_WEB_URL=https://serverless-100009469796.coding.net/p/ssr-coding-ci
[2022-01-10 14:10:43] FETCH_REF_SPECS=+refs/heads/*:refs/remotes/origin/* +refs/merge/*:refs/remotes/origin/merge/*
[2022-01-10 14:10:43] LOGNAME=root
[2022-01-10 14:10:43] NODE_NAME=master
[2022-01-10 14:10:43] PROJECT_NAME=ssr-coding-ci
[2022-01-10 14:10:43] HELM3_BIN=/root/programs/helm-v3.3.4-linux-amd64/linux-amd64
[2022-01-10 14:10:43] CODE_URL=https://serverless-templates-1300862921.cos.ap-beijing.myqcloud.com/http/nestjs.zip
[2022-01-10 14:10:43] RBENV_BIN=/root/.rbenv/bin
[2022-01-10 14:10:43] _=/usr/bin/daemon
[2022-01-10 14:10:43] STAGE_NAME=Initializing node.js environment
[2022-01-10 14:10:43] EXECUTOR_NUMBER=0
[2022-01-10 14:10:43] XDG_SESSION_ID=c1
[2022-01-10 14:10:43] RBENV_SHELL=su
[2022-01-10 14:10:43] BUILD_DISPLAY_NAME=#1
[2022-01-10 14:10:43] HUDSON_HOME=/var/lib/jenkins
[2022-01-10 14:10:43] JOB_BASE_NAME=cci-14726523-392077
[2022-01-10 14:10:43] PATH=/root/.rbenv/shims:/root/programs/apache-maven-3.6.3/bin:/root/programs/go/bin:/root/programs/gradle-7.0.2/bin:/root/programs/helm-v2.16.9-linux-amd64/linux-amd64:/root/programs/helm-v3.3.4-linux-amd64/linux-amd64:/root/programs/packer_1.6.0_linux_amd64:/root/programs/terraform_0.12.26_linux_amd64:/usr/lib/jvm/java-8-openjdk-amd64/bin:/root/.rbenv/bin:/root/programs/rancher-v2.4.5:/root/go/bin:/root/programs/pack-v0.14.2-linux:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
[2022-01-10 14:10:43] TENCENT_TEMP_SECRET_ID=******
[2022-01-10 14:10:43] TRIGGER_USER_NAME=serverless-100009469796
[2022-01-10 14:10:43] BUILD_ID=1
[2022-01-10 14:10:43] XDG_RUNTIME_DIR=/run/user/0
[2022-01-10 14:10:43] BUILD_TAG=jenkins-cci-14726523-392077-1
[2022-01-10 14:10:43] PROJECT_ID=8623005
[2022-01-10 14:10:43] JENKINS_URL=http://124.223.43.228:15730/
[2022-01-10 14:10:43] LANG=en_US.UTF-8
[2022-01-10 14:10:43] MVNW_REPOURL=http://mirrors.tencentyun.com/nexus/repository/maven-public/
[2022-01-10 14:10:43] JOB_URL=http://124.223.43.228:15730/job/cci-14726523-392077/
[2022-01-10 14:10:43] BUILD_NUMBER=1
[2022-01-10 14:10:43] JENKINS_NODE_COOKIE=9df40dab-7ce5-47fe-9bf9-bbb84c96507a
[2022-01-10 14:10:43] SHELL=/bin/bash
[2022-01-10 14:10:43] GOPATH=/root/go
[2022-01-10 14:10:43] GOPROXY=http://mirrors.tencentyun.com/go/
[2022-01-10 14:10:43] CCI_JOB_NAME=ssr-coding-ci-serverless-002
[2022-01-10 14:10:43] GOPATH_BIN=/root/go/bin
[2022-01-10 14:10:43] RUN_DISPLAY_URL=http://124.223.43.228:15730/job/cci-14726523-392077/1/display/redirect
[2022-01-10 14:10:43] CODING_ARTIFACTS_CREDENTIALS_ID=c6b4979c-3237-4481-bad5-4cbe0bacf22e
[2022-01-10 14:10:43] TENCENT_TEMP_TOKEN=******
[2022-01-10 14:10:43] HUDSON_SERVER_COOKIE=d208e4a5f08af5dd
[2022-01-10 14:10:43] TRIGGER_USER_ID=8147936
[2022-01-10 14:10:43] JOB_DISPLAY_URL=http://124.223.43.228:15730/job/cci-14726523-392077/display/redirect
[2022-01-10 14:10:43] JAVA_BIN=/usr/lib/jvm/java-8-openjdk-amd64/bin
[2022-01-10 14:10:43] ANDROID_SDK_ROOT=/root/programs/android-sdk
[2022-01-10 14:10:43] CCI_TRIGGER_METHOD=MANUAL
[2022-01-10 14:10:43] JOB_NAME=cci-14726523-392077
[2022-01-10 14:10:43] PWD=/root/workspace
[2022-01-10 14:10:43] RANCHER_BIN=/root/programs/rancher-v2.4.5
[2022-01-10 14:10:43] JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
[2022-01-10 14:10:43] PROJECT_TOKEN=******
[2022-01-10 14:10:43] XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
[2022-01-10 14:10:43] CCI_CURRENT_WEB_PROTOCOL=https
[2022-01-10 14:10:43] ANDROID_HOME=/root/programs/android-sdk
[2022-01-10 14:10:43] TRIGGER_USER_GK=GMjjBivYuL
[2022-01-10 14:10:43] CI_STORAGE_BUCKET_NAME=******
[2022-01-10 14:10:43] TENCENT_TEMP_SECRET_KEY=******
[2022-01-10 14:10:43] CCI_CURRENT_PROJECT_COMMON_CREDENTIALS_ID=c6b4979c-3237-4481-bad5-4cbe0bacf22e
[2022-01-10 14:10:43] CCI_TASK_NAME=cci-14726523-392077
[2022-01-10 14:10:43] GO_BIN=/root/programs/go/bin
[2022-01-10 14:10:43] CCI_CURRENT_DOMAIN=coding.net
[2022-01-10 14:10:43] + date
[2022-01-10 14:10:43] Mon Jan 10 14:10:43 CST 2022
[2022-01-10 14:10:43] + echo TENCENT_SECRET_ID=******
[2022-01-10 14:10:44] + echo TENCENT_SECRET_KEY=******
[2022-01-10 14:10:44] + echo TENCENT_TOKEN=******
[2022-01-10 14:10:44] + echo TENCENT_APP_ID=
[2022-01-10 14:10:45] + echo SERVERLESS_PLATFORM_VENDOR=tencent
[2022-01-10 14:10:45] + echo SERVERLESS_PLATFORM_STAGE=
[2022-01-10 14:10:45] + pnpm install -g serverless
[2022-01-10 14:10:48] Progress: resolved 1, reused 0, downloaded 0, added 0
[2022-01-10 14:10:49] Progress: resolved 52, reused 51, downloaded 0, added 0
[2022-01-10 14:10:49] Progress: resolved 52, reused 52, downloaded 0, added 0
[2022-01-10 14:10:50] Progress: resolved 56, reused 56, downloaded 0, added 0
[2022-01-10 14:10:52] Progress: resolved 57, reused 56, downloaded 0, added 0
[2022-01-10 14:10:53] Progress: resolved 146, reused 146, downloaded 0, added 0
[2022-01-10 14:10:53] Progress: resolved 147, reused 146, downloaded 0, added 0
[2022-01-10 14:10:53] Progress: resolved 282, reused 282, downloaded 0, added 0
[2022-01-10 14:10:53] Progress: resolved 283, reused 282, downloaded 0, added 0
[2022-01-10 14:10:54] Progress: resolved 410, reused 401, downloaded 0, added 0
[2022-01-10 14:10:54] Progress: resolved 411, reused 401, downloaded 0, added 0
[2022-01-10 14:10:56] Progress: resolved 524, reused 509, downloaded 0, added 0
[2022-01-10 14:10:56] Progress: resolved 525, reused 509, downloaded 0, added 0
[2022-01-10 14:10:56]  WARN  serverless > @serverless/components: inquirer-autocomplete-prompt@1.4.0 requires a peer of inquirer@^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0 but none was installed.
[2022-01-10 14:10:57] Already up-to-date
[2022-01-10 14:10:57] Progress: resolved 598, reused 597, downloaded 0, added 0, done
[2022-01-10 14:10:57] 
[2022-01-10 14:10:57] + sls -v
[2022-01-10 14:10:59] Framework Core: 2.70.0
[2022-01-10 14:10:59] Plugin: 5.5.3
[2022-01-10 14:10:59] SDK: 4.3.0
[2022-01-10 14:10:59] Components: 3.18.1
[2022-01-10 14:10:59] Serverless: Deprecation warning: Support for Node.js versions below v12 will be dropped with next major release. Please upgrade at https://nodejs.org/en/
[2022-01-10 14:10:59]             More Info: https://www.serverless.com/framework/docs/deprecations/#OUTDATED_NODEJS
[2022-01-10 14:10:59] + cat
[2022-01-10 14:11:00] + cat npm.sh
[2022-01-10 14:11:00] #! /bin/bash
[2022-01-10 14:11:00] rootPath=`pwd`
[2022-01-10 14:11:00] function read_dir(){
[2022-01-10 14:11:00]   for file in `ls $1`
[2022-01-10 14:11:00]   do
[2022-01-10 14:11:00]     if [ -d $1'/'$file ]; then
[2022-01-10 14:11:00]       if [ $file != 'node_modules' ]; then
[2022-01-10 14:11:00]         read_dir $1'/'$file
[2022-01-10 14:11:00]       fi
[2022-01-10 14:11:00]     else
[2022-01-10 14:11:00]       if [ $file = 'package.json' ]; then
[2022-01-10 14:11:00]         cd $1
[2022-01-10 14:11:00]         npm install
[2022-01-10 14:11:00]         cd $rootPath
[2022-01-10 14:11:00]       fi
[2022-01-10 14:11:00]     fi
[2022-01-10 14:11:00]   done
[2022-01-10 14:11:00] }
[2022-01-10 14:11:00] read_dir $1
[2022-01-10 14:11:00] + ls -la
[2022-01-10 14:11:00] total 312
[2022-01-10 14:11:00] drwxr-xr-x   6 root root   4096 Jan 10 14:10 .
[2022-01-10 14:11:00] drwx------  24 root root   4096 Jan 10 14:10 ..
[2022-01-10 14:11:00] drwxr-xr-x   2 root root   4096 Jan 10 14:10 dist
[2022-01-10 14:11:00] -rw-r--r--   1 root root    671 Jan 10 14:10 .env
[2022-01-10 14:11:00] -rw-r--r--   1 root root    631 Jul 26 16:18 .eslintrc.js
[2022-01-10 14:11:00] -rw-r--r--   1 root root   6724 Jul 26 16:18 .gitignore
[2022-01-10 14:11:00] -rw-r--r--   1 root root     64 Jul 26 16:18 nest-cli.json
[2022-01-10 14:11:00] drwxr-xr-x 495 root root  20480 Jan 10 14:10 node_modules
[2022-01-10 14:11:00] -rw-r--r--   1 root root    330 Jan 10 14:10 npm.sh
[2022-01-10 14:11:00] -rw-r--r--   1 root root   2006 Jul 26 16:18 package.json
[2022-01-10 14:11:00] -rw-r--r--   1 root root     51 Jul 26 16:18 .prettierrc
[2022-01-10 14:11:00] -rw-r--r--   1 root root   3392 Jul 26 16:18 README.md
[2022-01-10 14:11:00] -rw-r--r--   1 root root    234 Jul 26 16:18 serverless.yml
[2022-01-10 14:11:00] drwxr-xr-x   2 root root   4096 Jan 10 14:10 src
[2022-01-10 14:11:00] -rw-r--r--   1 root root     97 Jul 26 16:18 tsconfig.build.json
[2022-01-10 14:11:00] -rw-r--r--   1 root root    365 Jul 26 16:18 tsconfig.json
[2022-01-10 14:11:00] drwxr-xr-x   2 root root   4096 Jan 10 14:10 views
[2022-01-10 14:11:00] -rw-r--r--   1 root root 225677 Jul 26 16:18 yarn.lock
[2022-01-10 14:11:00] + rm -rf ./node_modules
[2022-01-10 14:11:01] + chmod +x ./npm.sh
[2022-01-10 14:11:01] + pwd
[2022-01-10 14:11:01] + ./npm.sh /root/workspace
[2022-01-10 14:11:33] 
[2022-01-10 14:11:33] > @nestjs/core@8.2.4 postinstall /root/workspace/node_modules/@nestjs/core
[2022-01-10 14:11:33] > opencollective || exit 0
[2022-01-10 14:11:33] 
[2022-01-10 14:11:33] npm notice created a lockfile as package-lock.json. You should commit this file.
[2022-01-10 14:11:33] npm WARN notsup Unsupported engine for ts-loader@9.2.6: wanted: {"node":">=12.0.0"} (current: {"node":"10.21.0","npm":"6.14.4"})
[2022-01-10 14:11:33] npm WARN notsup Not compatible with your version of node/npm: ts-loader@9.2.6
[2022-01-10 14:11:33] npm WARN notsup Unsupported engine for @angular-devkit/core@13.1.1: wanted: {"node":"^12.20.0 || ^14.15.0 || >=16.10.0","npm":"^6.11.0 || ^7.5.6 || >=8.0.0","yarn":">= 1.13.0"} (current: {"node":"10.21.0","npm":"6.14.4"})
[2022-01-10 14:11:33] npm WARN notsup Not compatible with your version of node/npm: @angular-devkit/core@13.1.1
[2022-01-10 14:11:33] npm WARN notsup Unsupported engine for @angular-devkit/schematics@13.1.1: wanted: {"node":"^12.20.0 || ^14.15.0 || >=16.10.0","npm":"^6.11.0 || ^7.5.6 || >=8.0.0","yarn":">= 1.13.0"} (current: {"node":"10.21.0","npm":"6.14.4"})
[2022-01-10 14:11:33] npm WARN notsup Not compatible with your version of node/npm: @angular-devkit/schematics@13.1.1
[2022-01-10 14:11:33] npm WARN notsup Unsupported engine for @angular-devkit/schematics-cli@13.1.1: wanted: {"node":"^12.20.0 || ^14.15.0 || >=16.10.0","npm":"^6.11.0 || ^7.5.6 || >=8.0.0","yarn":">= 1.13.0"} (current: {"node":"10.21.0","npm":"6.14.4"})
[2022-01-10 14:11:33] npm WARN notsup Not compatible with your version of node/npm: @angular-devkit/schematics-cli@13.1.1
[2022-01-10 14:11:33] npm WARN notsup Unsupported engine for @angular-devkit/core@13.0.2: wanted: {"node":"^12.20.0 || ^14.15.0 || >=16.10.0","npm":"^6.11.0 || ^7.5.6 || >=8.0.0","yarn":">= 1.13.0"} (current: {"node":"10.21.0","npm":"6.14.4"})
[2022-01-10 14:11:33] npm WARN notsup Not compatible with your version of node/npm: @angular-devkit/core@13.0.2
[2022-01-10 14:11:33] npm WARN notsup Unsupported engine for @angular-devkit/schematics@13.0.2: wanted: {"node":"^12.20.0 || ^14.15.0 || >=16.10.0","npm":"^6.11.0 || ^7.5.6 || >=8.0.0","yarn":">= 1.13.0"} (current: {"node":"10.21.0","npm":"6.14.4"})
[2022-01-10 14:11:33] npm WARN notsup Not compatible with your version of node/npm: @angular-devkit/schematics@13.0.2
[2022-01-10 14:11:33] npm WARN notsup Unsupported engine for fs-extra@10.0.0: wanted: {"node":">=12"} (current: {"node":"10.21.0","npm":"6.14.4"})
[2022-01-10 14:11:33] npm WARN notsup Not compatible with your version of node/npm: fs-extra@10.0.0
[2022-01-10 14:11:33] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/chokidar/node_modules/fsevents):
[2022-01-10 14:11:33] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[2022-01-10 14:11:33] npm WARN notsup Unsupported engine for @cspotcode/source-map-support@0.7.0: wanted: {"node":">=12"} (current: {"node":"10.21.0","npm":"6.14.4"})
[2022-01-10 14:11:33] npm WARN notsup Not compatible with your version of node/npm: @cspotcode/source-map-support@0.7.0
[2022-01-10 14:11:33] npm WARN notsup Unsupported engine for @cspotcode/source-map-consumer@0.8.0: wanted: {"node":">= 12"} (current: {"node":"10.21.0","npm":"6.14.4"})
[2022-01-10 14:11:33] npm WARN notsup Not compatible with your version of node/npm: @cspotcode/source-map-consumer@0.8.0
[2022-01-10 14:11:33] npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
[2022-01-10 14:11:33] 
[2022-01-10 14:11:33] added 818 packages from 541 contributors and audited 822 packages in 28.793s
[2022-01-10 14:11:33] 
[2022-01-10 14:11:33] 80 packages are looking for funding
[2022-01-10 14:11:33]   run `npm fund` for details
[2022-01-10 14:11:33] 
[2022-01-10 14:11:33] found 0 vulnerabilities
[2022-01-10 14:11:33] 
[2022-01-10 14:11:33] + rm npm.sh
[2022-01-10 14:11:33] + npm i @slsplus/yaml-parser -g
[2022-01-10 14:11:34] npm WARN deprecated @types/ora@3.2.0: This is a stub types definition. ora provides its own type definitions, so you do not need this installed.
[2022-01-10 14:11:36] /usr/bin/yparse -> /usr/lib/node_modules/@slsplus/yaml-parser/bin/yparse.js
[2022-01-10 14:11:36] + @slsplus/yaml-parser@0.1.2
[2022-01-10 14:11:36] added 70 packages from 132 contributors in 2.423s
[2022-01-10 14:11:36] + yparse --output --auto-create --sls-options={"component":"http","name":"http-nestjs-95oruVZdv","org":"1258804183","app":"serverless-002","stage":"dev","inputs":{"region":"ap-guangzhou","src":{"src":"./","dist":"./","hook":"npm run build","exclude":[".env"]},"isAutoCiDeploy":false,"faas":{"runtime":"Nodejs12.16","eip":false,"timeout":3,"memorySize":512,"tags":[],"framework":"nestjs","environments":[]},"apigw":{"timeout":60,"protocols":["http","https"],"environment":"release","customDomains":[]}}}
[2022-01-10 14:11:36] 
[2022-01-10 14:11:36] Parse success, and output to file path /root/workspace/serverless.yml
[2022-01-10 14:11:36] 
[2022-01-10 14:11:36] + cat serverless.yml
[2022-01-10 14:11:36] component: http
[2022-01-10 14:11:36] name: http-nestjs-95oruVZdv
[2022-01-10 14:11:36] inputs:
[2022-01-10 14:11:36]   src:
[2022-01-10 14:11:36]     dist: ./
[2022-01-10 14:11:36]     hook: npm run build
[2022-01-10 14:11:36]     exclude:
[2022-01-10 14:11:36]       - .env
[2022-01-10 14:11:36]     src: ./
[2022-01-10 14:11:36]   faas:
[2022-01-10 14:11:36]     runtime: Nodejs12.16
[2022-01-10 14:11:36]     framework: nestjs
[2022-01-10 14:11:36]     name: '${name}'
[2022-01-10 14:11:36]     eip: false
[2022-01-10 14:11:36]     timeout: 3
[2022-01-10 14:11:36]     memorySize: 512
[2022-01-10 14:11:36]     tags: []
[2022-01-10 14:11:36]     environments: []
[2022-01-10 14:11:36]   apigw:
[2022-01-10 14:11:36]     protocols:
[2022-01-10 14:11:36]       - http
[2022-01-10 14:11:36]       - https
[2022-01-10 14:11:36]     timeout: 60
[2022-01-10 14:11:36]     environment: release
[2022-01-10 14:11:36]     customDomains: []
[2022-01-10 14:11:36]   region: ap-guangzhou
[2022-01-10 14:11:36]   isAutoCiDeploy: false
[2022-01-10 14:11:36] org: '1258804183'
[2022-01-10 14:11:36] app: serverless-002
[2022-01-10 14:11:36] stage: dev
[2022-01-10 14:11:37] + yparse --output --auto-create --layer-options={"org":"1258804183","app":"serverless-002","stage":"dev","runtime":"Nodejs12.16","region":"ap-guangzhou"}
[2022-01-10 14:11:37] 
[2022-01-10 14:11:37] Parse success, and output to file path /root/workspace/serverless.yml
[2022-01-10 14:11:37] 
[2022-01-10 14:11:37] + cat layer/serverless.yml
[2022-01-10 14:11:37] org: '1258804183'
[2022-01-10 14:11:37] app: serverless-002
[2022-01-10 14:11:37] stage: dev
[2022-01-10 14:11:37] component: layer
[2022-01-10 14:11:37] name: serverless-002-layer
[2022-01-10 14:11:37] inputs:
[2022-01-10 14:11:37]   name: serverless-002-layer
[2022-01-10 14:11:37]   region: ap-guangzhou
[2022-01-10 14:11:37]   src:
[2022-01-10 14:11:37]     src: ../node_modules
[2022-01-10 14:11:37]     targetDir: /node_modules
[2022-01-10 14:11:37]   runtimes:
[2022-01-10 14:11:37]     - Nodejs12.16
[2022-01-10 14:11:37] + ls -la
[2022-01-10 14:11:37] total 612
[2022-01-10 14:11:37] drwxr-xr-x   7 root root   4096 Jan 10 14:11 .
[2022-01-10 14:11:37] drwx------  24 root root   4096 Jan 10 14:10 ..
[2022-01-10 14:11:37] drwxr-xr-x   2 root root   4096 Jan 10 14:10 dist
[2022-01-10 14:11:37] -rw-r--r--   1 root root    671 Jan 10 14:10 .env
[2022-01-10 14:11:37] -rw-r--r--   1 root root    631 Jul 26 16:18 .eslintrc.js
[2022-01-10 14:11:37] -rw-r--r--   1 root root   6724 Jul 26 16:18 .gitignore
[2022-01-10 14:11:37] drwxr-xr-x   2 root root   4096 Jan 10 14:11 layer
[2022-01-10 14:11:37] -rw-r--r--   1 root root     64 Jul 26 16:18 nest-cli.json
[2022-01-10 14:11:37] drwxr-xr-x 493 root root  20480 Jan 10 14:11 node_modules
[2022-01-10 14:11:37] -rw-r--r--   1 root root   2006 Jul 26 16:18 package.json
[2022-01-10 14:11:37] -rw-r--r--   1 root root 303379 Jan 10 14:11 package-lock.json
[2022-01-10 14:11:37] -rw-r--r--   1 root root     51 Jul 26 16:18 .prettierrc
[2022-01-10 14:11:37] -rw-r--r--   1 root root   3392 Jul 26 16:18 README.md
[2022-01-10 14:11:37] -rw-r--r--   1 root root    657 Jan 10 14:11 serverless.yml
[2022-01-10 14:11:37] drwxr-xr-x   2 root root   4096 Jan 10 14:10 src
[2022-01-10 14:11:37] -rw-r--r--   1 root root     97 Jul 26 16:18 tsconfig.build.json
[2022-01-10 14:11:37] -rw-r--r--   1 root root    365 Jul 26 16:18 tsconfig.json
[2022-01-10 14:11:37] drwxr-xr-x   2 root root   4096 Jan 10 14:10 views
[2022-01-10 14:11:37] -rw-r--r--   1 root root 225677 Jul 26 16:18 yarn.lock
[2022-01-10 14:11:37] + serverless deploy --debug --target=./layer
[2022-01-10 14:11:40] 正在初始化...
[2022-01-10 14:11:40] Action: "deploy" - Stage: "dev" - App: "serverless-002" - Name: "serverless-002-layer"
[2022-01-10 14:11:40] 准备中...
[2022-01-10 14:11:50] 当前项目文件大小超过200MB，部署有可能会失败。如果失败建议使用 Webpack, Parcel 或 Layer 来减小项目文件大小后重试
[2022-01-10 14:12:37] 上传中...
[2022-01-10 14:12:37] 部署中...
[2022-01-10 14:12:46] region:      ap-guangzhou
[2022-01-10 14:12:46] name:        serverless-002-layer
[2022-01-10 14:12:46] bucket:      sls-layer-ap-guangzhou-code
[2022-01-10 14:12:46] object:      serverless-002-layer-1641795160.zip
[2022-01-10 14:12:46] description: Layer created by serverless component
[2022-01-10 14:12:46] runtimes: 
[2022-01-10 14:12:46]   - Nodejs12.16
[2022-01-10 14:12:46] version:     1
[2022-01-10 14:12:46] 应用控制台: https://serverless.cloud.tencent.com/apps/serverless-002/serverless-002-layer/dev
[2022-01-10 14:12:46] 67s › serverless-002-layer › 执行成功
[2022-01-10 14:12:46] 
[2022-01-10 14:12:46] 
[2022-01-10 14:12:47] + serverless deploy --debug --force
[2022-01-10 14:12:48] 正在初始化...
[2022-01-10 14:12:48] Action: "deploy" - Stage: "dev" - App: "serverless-002" - Name: "http-nestjs-95oruVZdv"
[2022-01-10 14:12:50] 
[2022-01-10 14:12:50]  Error: "src.hook" 执行失败: "npm run build", 错误信息: RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
[2022-01-10 14:12:50]     at exec (/usr/pnpm-global/4/node_modules/.pnpm/@serverless/platform-client-china@2.3.4/node_modules/@serverless/platform-client-china/src/instance.js:186:21)
[2022-01-10 14:12:50]     at ChildProcess.exithandler (child_process.js:301:5)
[2022-01-10 14:12:50]     at ChildProcess.emit (events.js:198:13)
[2022-01-10 14:12:50]     at maybeClose (internal/child_process.js:982:16)
[2022-01-10 14:12:50]     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
[2022-01-10 14:12:50] 
[2022-01-10 14:12:50] 2s › http-nestjs-95oruVZdv › "src.hook" 执行失败: "npm run build", 错误信息: RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded 
[2022-01-10 14:12:50] 
[2022-01-10 14:12:50]   帮助文档: https://www.serverless.com/cn/framework/docs/ 
[2022-01-10 14:12:50]   BUG提交: https://github.com/serverless/serverless-tencent/issues 
[2022-01-10 14:12:50]   问答社区: https://github.com/serverless/serverless-tencent/discussions 
[2022-01-10 14:12:50] 
[2022-01-10 14:12:50] 
[2022-01-10 14:13:05] 
script returned exit code 1

<details>
<summary>环境版本</summary>

```yaml
- requestId: ... # 如果在异常信息中显示请提供
- traceId: ... # 如果在异常信息中显示请提供
- 操作系统(OS): ... # 如: MacOS 11.2.3
- Node 版本: ... # 如: 12.20.1
# 使用 "serverless --version" 查看serverless版本信息
- Components 版本: ... # 如: 3.7.2
- Framework 版本: ... # 如: 2.28.7
- SDK 版本: ... # 如: 2.3.2
```

</details>

---

<details>
<summary>serverless.yml 配置</summary>

```yaml
# 在这里填写完整的serverless.yml配置信息
```

</details>

---

<details>
<summary>DEBUG 输出</summary>

```yml
# 添加环境变量 SLS_DEBUG=* 并重新执行命令，然后复制命令以及控制台输出粘贴在这里。
```

</details>

**Comment by Rong5180** [comment]
创建应用时由于文件或网络其他原因可能会存在部署失败的情况，重新创建就能成功了

**Comment by ole3021** [comment]
@FrankyLee-dev  这个使用模板创建我这里测试是可以正常创建的，不过因为项目文件中大小超过200M，在部署时候有可能会因为空间不够导致部署失败，上面错误消息看就是这个错误。 可以重试一下。 

或者是个人项目可以考虑使用 Layer 减少代码包体积来进行部署，相关内容可以参考： https://cn-serverless.webflow.io/blog/deploy-nextjs-gracely 的 “基于 Layer 部署 node_modules” 部分。

**Comment by weipengzou** [comment]
> @FrankyLee-dev 这个使用模板创建我这里测试是可以正常创建的，不过因为项目文件中大小超过200M，在部署时候有可能会因为空间不够导致部署失败，上面错误消息看就是这个错误。 可以重试一下。
> 
> 或者是个人项目可以考虑使用 Layer 减少代码包体积来进行部署，相关内容可以参考： https://cn-serverless.webflow.io/blog/deploy-nextjs-gracely 的 “基于 Layer 部署 node_modules” 部分。
腾讯云serverless的 Layer 上传限制了50M大小，node_modules 压缩后都超过了50M怎么办😂
